apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    app: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: janmenjaya/login
        ports:
        - containerPort: 30003  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0    

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: login
  name: login
  namespace: default
spec:
  clusterIP: 10.110.193.62
  clusterIPs:
  - 10.110.193.62
  internalTrafficPolicy: Cluster
  ports:
  - port: 30003
    protocol: TCP
    targetPort: 30003
  selector:
    app: login
  sessionAffinity: None
  type: ClusterIP
